trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: Build Java Application
  jobs:
  - job: MavenBuild
    displayName: Maven Build
    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      displayName: Maven Build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests'
        publishJUnitResults: false

    - task: PublishPipelineArtifact@1
      displayName: Publish JAR
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/target'
        artifact: 'java-artifact'


- stage: BuildImage
  displayName: Build Docker Image
  dependsOn: Build
  jobs:
  - job: DockerBuild
    displayName: Docker Build
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: Download JAR
      inputs:
        artifact: 'java-artifact'
        path: '$(System.DefaultWorkingDirectory)/target'

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        repository: 'java-hello-world'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest